// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqHFzBRtyCiyZ3YLiHtAVJbDTYD71W-V8',
    appId: '1:491348943166:web:500aa080071a3fadb18c6f',
    messagingSenderId: '491348943166',
    projectId: 'doctor-appointment-app-ad8f8',
    authDomain: 'doctor-appointment-app-ad8f8.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-ad8f8.firebasestorage.app',
    measurementId: 'G-VC14B87C8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx1F04w413gTBa7pSrP9BGSF7J6AdXASE',
    appId: '1:491348943166:android:f984330c45dee4f6b18c6f',
    messagingSenderId: '491348943166',
    projectId: 'doctor-appointment-app-ad8f8',
    storageBucket: 'doctor-appointment-app-ad8f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU8QHCG8njz5VOWShz-GsXPVDdcZw5toA',
    appId: '1:491348943166:ios:48feb5e014f28b2bb18c6f',
    messagingSenderId: '491348943166',
    projectId: 'doctor-appointment-app-ad8f8',
    storageBucket: 'doctor-appointment-app-ad8f8.firebasestorage.app',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU8QHCG8njz5VOWShz-GsXPVDdcZw5toA',
    appId: '1:491348943166:ios:48feb5e014f28b2bb18c6f',
    messagingSenderId: '491348943166',
    projectId: 'doctor-appointment-app-ad8f8',
    storageBucket: 'doctor-appointment-app-ad8f8.firebasestorage.app',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqHFzBRtyCiyZ3YLiHtAVJbDTYD71W-V8',
    appId: '1:491348943166:web:6de7d0879c95c15fb18c6f',
    messagingSenderId: '491348943166',
    projectId: 'doctor-appointment-app-ad8f8',
    authDomain: 'doctor-appointment-app-ad8f8.firebaseapp.com',
    storageBucket: 'doctor-appointment-app-ad8f8.firebasestorage.app',
    measurementId: 'G-PSK1EY2WXX',
  );
}
